// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLUNNW4Ab5HCywEG5AdUHk0vlSPevHhk',
    appId: '1:188371728581:android:dac237381130157e2098ac',
    messagingSenderId: '188371728581',
    projectId: 'trialproject-9f7bf',
    databaseURL: 'https://trialproject-9f7bf-default-rtdb.firebaseio.com',
    storageBucket: 'trialproject-9f7bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yLKst_4tc02tlMDpHBeLjrn4Hui9MMk',
    appId: '1:188371728581:ios:9891b68d0c2aa38f2098ac',
    messagingSenderId: '188371728581',
    projectId: 'trialproject-9f7bf',
    databaseURL: 'https://trialproject-9f7bf-default-rtdb.firebaseio.com',
    storageBucket: 'trialproject-9f7bf.appspot.com',
    iosClientId: '188371728581-a9i56pjnuh6bq2rh4maj2fr62a7hglnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.jacksonApp',
  );
}
